server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    config:
      uri: http://config.platform:8888

eureka:
  client:
    service-url:
      defaultZone: http://vm-node-a.platform:8761/eureka,http://vm-node-b.platform:8761/eureka,http://vm-node-c.platform:8761/eureka
    instance:
      prefer-ip-address: true