server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:


management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,routes

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG