eureka:
  client:
    service-url:
      defaultZone: http://vm-node-a.platform:8888/eureka,http://vm-node-b.platform:8888/eureka,http://vm-node-c.platform:8888/eureka
  instance:
    prefer-ip-address: true